apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger
  
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: luna_testing
    user: luna
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    secureJsonData:
      password: ${REDIS_PASSWORD}
    jsonData:
      client: standalone